package io.carpe.scalambda.conf

import java.io.File

import io.carpe.scalambda.conf.function.{ApiGatewayConf, FunctionConf}
import io.carpe.scalambda.conf.utils.StringUtils

case class ScalambdaFunction(functionName: String,
                             handlerPath: String,
                             functionConfig: FunctionConf,
                             apiConfig: Option[ApiGatewayConf],
                             assemblyPath: File,
                             s3BucketName: String
                            ) {

  /**
   * This will be the name of the terraform lambda resource generated by the "scalambdaTerraform" task.
   */
  lazy val terraformLambdaResourceName: String = {
    val snakeCaseFunctionName = StringUtils.toSnakeCase(functionName)
    s"${snakeCaseFunctionName}_lambda"
  }

  /**
   * Create a variable in the outputted yaml that the terraform will inject the actual arn into once the lambda has
   * been created.
   *
   * This makes sure that our swagger file uses the proper lambda invocation ARN.
   */
  lazy val swaggerVariableName: String = {
    """${""" + terraformLambdaResourceName  + """_invoke_arn}"""
  }

  /**
   * This will be the name of the terraform resource representing the s3 bucket this lambda's code is stored in
   */
  lazy val terraformS3BucketResourceName: String = {
    StringUtils.toSnakeCase(s3BucketName)
  }

  /**
   * This will be the name of the terraform resource representing the s3 bucket item that is the lambda's code
   */
  lazy val terraformS3BucketItemResourceName: String = {
    StringUtils.toSnakeCase(functionName)
  }

}