package io.carpe.scalambda.terraform.ast

import cats.data.Chain
import io.carpe.scalambda.terraform.ast.props.TLine
import io.carpe.scalambda.terraform.ast.props.TLine.{TBlockLine, TEmptyLine}

case class TerraformFile(definitions: Seq[Definition], fileName: String) {
  lazy val definitionsChain: Chain[Definition] = Chain.fromSeq(definitions)
}

object TerraformFile {
  lazy val fileHeader: String = "# This file was autogenerated by the scalambdaTerraform command from the Scalambda SBT plugin!"
  lazy val fileHeaderChain: Chain[TLine] = {
    Chain(
      TBlockLine(0, fileHeader),
      TEmptyLine
    )
  }
}
